name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cityscapes:latest
    - name: login
      run: docker login -u mou6969 -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Tag the Docker image
      run: docker tag cityscapes:latest mou6969/cityscapes_moustafa:latest
    - name: push the Docker image
      run: docker push mou6969/cityscapes_moustafa:latest
